### ISSUE TITLE
Filter comic books from regular books

### ISSUE THREAD

**Issue by Mimaaa** [rijkvanzanten/obachine#109]

**Comment by Mimaaa** [comment]
Is this even possible @rijkvanzanten @pierman1 ?

**Comment by rijkvanzanten** [comment]
<img width="1099" alt="screen shot 2017-06-23 at 20 35 04" src="https://user-images.githubusercontent.com/9141017/27495746-797e9f6a-5853-11e7-9eb2-de39e93e9d4e.png">


I don't think filtering by comic books is possible within the API
