### ISSUE TITLE
Close modal if you change your mind

### ISSUE THREAD

**Issue by Mimaaa** [rijkvanzanten/obachine#123]
The current flow is: click on a filter -> modal opens -> select an option -> save. There's no option to close the modal if you change your mind and want to use another filter. You first need to save the input and then you get the option to remove the modal.

The users on who we tested disliked the flow. They thought they could click on the dimmed background or expected a close (cross) button in one of the upper corners.

**Comment by rijkvanzanten** [comment]
We've added the ability to close the modal by clicking the opaque background #137 . We won't implement  a close button due to time constraints
