### ISSUE TITLE
load @ middle of the page on detail (single.js) view

### ISSUE THREAD

**Issue by Mimaaa** [rijkvanzanten/obachine#47]
<img width="317" alt="screen shot 2017-06-14 at 10 21 09" src="https://user-images.githubusercontent.com/12242967/27122498-389956bc-50eb-11e7-9519-c6a240e1416d.png">

**Comment by pierman1** [comment]
Focus style?

**Comment by rijkvanzanten** [comment]
`window.scrollTop = 0;`

**Comment by Mimaaa** [comment]
See https://github.com/rijkvanzanten/obachine/pull/179
