### ISSUE TITLE
Use consistent branche names 

### ISSUE THREAD

**Issue by joostf** [rijkvanzanten/obachine#51]
<img width="364" alt="screen shot 2017-06-17 at 09 28 51" src="https://user-images.githubusercontent.com/1061632/27251086-708f654c-533f-11e7-9b88-e6bac522e1da.png">

**Comment by joostf** [comment]
<img width="364" alt="screen shot 2017-06-17 at 09 28 51" src="https://user-images.githubusercontent.com/1061632/27251086-708f654c-533f-11e7-9b88-e6bac522e1da.png">

**Comment by rijkvanzanten** [comment]
They shouldn't have been there in the first place. We've cleaned up the already merged and closed branches 👍
