### ISSUE TITLE
Why destructuring into a single variable?

### ISSUE THREAD

**Issue by joostf** [rijkvanzanten/obachine#52]
https://github.com/rijkvanzanten/obachine/commit/6e7f1e1cd6c3cafbaf98133220d3ab96ab2b8b3a#diff-2d5bbda346ebb54b9745d10f2fb5b1b6R18

**Comment by rijkvanzanten** [comment]
Because we can? ¯\\\_(ツ)_/¯ 

Also it saves a _whopping_ 4 characters
```javascript
const {query} = req;
const query = req.query;
```

**Comment by joostf** [comment]
Fair enough :+1:
