### ISSUE TITLE
Add animations

### ISSUE THREAD

**Issue by Mimaaa** [rijkvanzanten/obachine#68]
Which one tho?

[TweenJS](http://www.createjs.com/tweenjs) or [Greensock](https://greensock.com/)

**Comment by Mimaaa** [comment]
Greensock seems like the best choice @rijkvanzanten @pierman1 

https://css-tricks.com/comparison-animation-technologies/

**Comment by rijkvanzanten** [comment]
Neither one, we're going with [Snap SVG](http://snapsvg.io)

**Comment by Mimaaa** [comment]
We reconciled and chose native CSS Animations after all.

**Comment by pierman1** [comment]
Keyword filter animation, maybe some more to animate?

**Comment by pierman1** [comment]
Need new design machine
