### ISSUE TITLE
Styling of modals is off

### ISSUE THREAD

**Issue by rijkvanzanten** [rijkvanzanten/obachine#73]

**Comment by Mimaaa** [comment]
When taking on this issue please consider the following bug as well: https://github.com/rijkvanzanten/obachine/issues/39

A temporary fix was made.

**Comment by Mimaaa** [comment]
Fixed the modals on mobile (iPhone 5) on Chrome. Next step is testing everything on other browser.

https://github.com/rijkvanzanten/obachine/pull/99

**Comment by rijkvanzanten** [comment]
Well it isn't finished then is it?

**Comment by Mimaaa** [comment]
It kinda is. It works perfectly on Chrome in all modes. I would rather refer to a more general [issue](https://github.com/rijkvanzanten/obachine/issues/112) where everything needs to be checked after all.
